import json
import sys
import xlrd
import copy
import glob
from datetime import date
import os
import shutil


def retrieve_file_path(wd):
	try:
		wb = xlrd.open_workbook("{}/starlims_to_json.xls".format(wd))
		sheet = wb.sheet_by_index(0)
		starlims_files=[]
		concentration_files=[]
		indexes=[]
		index_ids=[]
		for i in range(1,sheet.nrows):
			#print(sheet.cell_value(i, 2))
			starlims_files.append(sheet.cell_value(i, 0))
			concentration_files.append(sheet.cell_value(i, 1))
			indexes.append(sheet.cell_value(i, 2))
			index_ids.append(sheet.cell_value(i, 3))
			batch_name=sheet.cell_value(i, 4)
			volume=sheet.cell_value(i, 5)
			concentration=sheet.cell_value(i, 6)
	except:
		f=open("{}/error.txt".format(wd),"w")
		f.write("starlims_to_json.xls saknas, eller är felformaterad!")
		quit()

	return(starlims_files, concentration_files, indexes, index_ids,batch_name,volume,concentration)

def read_index_file(index_per_well,index_id_per_well,index_file_path,index_id,wd):
	try:
		for line in open(index_file_path):
			content=line.strip().split()
			index_per_well[content[0]]="{} ({}-{})".format(content[1],content[2],content[3])
			index_id_per_well[content[0]]=index_id
	except:
		f=open("{}/error.txt".format(wd),"w")
		f.write("Kunde ej läsa index filen:{}".format(index_file_path))
		quit()
	return(index_per_well,index_id_per_well)


def read_concentration_file(sample_concentration_to_well,concentration_file_path,wd):

	wb = xlrd.open_workbook("{}/{}".format(wd,concentration_file_path))
	sheet = wb.sheet_by_index(0)
	rows=["A","B","C","D","E","F","G","H"]
	row=0
	for i in range(13,21):
		for j in range(1,13):
			sample_concentration_to_well[rows[row]+str(j)]=sheet.cell_value(i, j)
			
		row+=1		
		 
	return(sample_concentration_to_well)
	

main_template={
  "name": "Name",
  "customer": "cust032",
  "comment": "Automatically generated by the Handy Penguin",
  "samples": []
}

sample_template={
      "name": "SampleName",
      "application": "RMLP05R800",
      "data_analysis": "FLUFFY",
      "comment": "",
      "volume": "Volume",
      "concentration": "Concentration",
      "sample_concentration":"SampleConcentration",
      "pool": "Pool",
      "rml_plate_name": "PlateName",
      "well_position_rml": "WellPosition",
      "index": "Index",
      "index_number": "IndexNumber",
      "index_sequence": "IndexSequence",
      "capture_kit": "cfDNA",
      "priority": "standard"
}


wd=os.path.dirname(os.path.realpath(__file__))
starlims_files, concentration_files, indexes, index_id, name, volume, concentration=retrieve_file_path(wd)

print (indexes)
index_per_well={}
index_id_per_well={}
i=0
for index_file_path in indexes:
	index_per_well,index_id_per_well=read_index_file(index_per_well,index_id_per_well,index_file_path,index_id[i],wd)
	i+=1

sample_concentration_to_well={}
for concentration_file_path in concentration_files:
	sample_concentration_to_well=read_concentration_file(sample_concentration_to_well,concentration_file_path,wd)

sample_data=[]
for file in starlims_files:
	wb = xlrd.open_workbook(file)
	sheet = wb.sheet_by_index(0)

	for i in range(sheet.nrows):
		if i ==0:
			continue
		sample_data.append(copy.deepcopy(sample_template))
		well=sheet.cell_value(i, 13)+str(int(sheet.cell_value(i, 14)))
		sample_data[-1]["name"]=sheet.cell_value(i, 0)
		sample_data[-1]["rml_plate_name"]=sheet.cell_value(i, 15)
		sample_data[-1]["well_position_rml"]=well
		sample_data[-1]["index_number"]=int(index_per_well[ well ].split(" ")[0].replace("UDI",""))
		sample_data[-1]["index_sequence"]=index_per_well[ well ]
		sample_data[-1]["index"]=index_id_per_well[ well ]
		sample_data[-1]["pool"]=name
		sample_data[-1]["volume"]=volume
		sample_data[-1]["concentration"]=concentration
		sample_data[-1]["sample_concentration"]=sample_concentration_to_well[well]

current_date = date.today()
directory_path="analysis_{}_{}_{}".format(current_date.year,current_date.month,current_date.day)
try:
	os.mkdir(directory_path)

except:
	pass

for file in starlims_files:	
	shutil.move(file, directory_path)
for file in concentration_files:	
	shutil.move(file, directory_path)
shutil.move("{}/starlims_to_json.xls".format(wd), directory_path)


main_template["name"]=name
main_template["samples"]=sample_data
f=open("nipt_rml_{}_{}_{}.json".format(current_date.year,current_date.month,current_date.day),"w")
f.write(json.dumps(main_template)) 
f.close()
